# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "Card": "10_card.ipynb"}

modules = ["core.py",
           "card.py"]

doc_url = "https://StephanRempel.github.io/my_nbdev_tutorial/"

git_url = "https://github.com/StephanRempel/my_nbdev_tutorial/tree/master/"

def custom_doc_links(name): return None
